# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-29 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsvisitcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodschannel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='goods.GoodsCategory', verbose_name='顶级商品类别'),
        ),
    ]
