# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-29 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190529_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodschannelgroup',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodschannelgroup',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
