# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-01 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190529_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='goods.SPU', verbose_name='商品'),
        ),
    ]
